// AUTO-GENERATED by `npm run import` (scripts/import-exports.ts).
// A committed snapshot of recipes.json's size; loadExports.test.ts asserts the
// loaded registry still matches it, so a lossy edit to recipes.json fails loudly.
// Do not edit by hand — it is rewritten after every successful import.
export const REGISTRY_STATS = { recipes: 1169, crafters: 25 } as const
